# @package _global_

defaults:
  - /evaluate/LRS3_Test_True
  - _self_

result_root: ${project_root}/../metrics/model_out/LRS3-mini50/example
list_path: ${project_root}/data/dataset/LRS3_Test_True/LRS3_Test_mini50.txt
max_items: -1
